### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by sricodelli** [lucadello91/laravel-scout-elasticsearch#1]
```
'elasticsearch' => [
        'index' => env('ELASTICSEARCH_INDEX', 'laravel'),
        'hosts' => [
            env('ELASTICSEARCH_HOST', 'http://localhost:9200'),
        ],
        'max_result_window' => '200000'
    ],
```

What should be used in the index?

Do i just need to follow laravel scout algolia documentation for indexing on a model?
```
<?php

namespace App;

use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use Searchable;

    /**
     * Get the index name for the model.
     *
     * @return string
     */
    public function searchableAs()
    {
        return 'posts_index';
    }
}
```

and then `php artisan scout:import "App\Post"`

I'm unable to find any information on this,

**Comment by lucadello91** [comment]
Hi
the index field in config, is the index used by Elasticsearch. 
You can use everything you would, it represent your application.
The index will be created automatically on Elasticsearch.

The `serchableAs()` represent the model type on Elastichsearch.

You can find a simple explanation here:

> The easiest and most familiar layout clones what you would expect from a relational database. You can (very roughly) think of an index like a database.
MySQL => Databases => Tables => Columns/Rows
Elasticsearch => Indices => Types => Documents with Properties
An Elasticsearch cluster can contain multiple Indices (databases), which in turn contain multiple Types (tables). These types hold multiple Documents (rows), and each document has Properties(columns).

Quote source: [What is an Elasticsearch Index?](https://www.elastic.co/blog/what-is-an-elasticsearch-index)

For importing data, you should follow Laravel Scout Docs.
